export const PRODUCTS = {
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    FETCH_PRODUCTS_STARTED: "FETCH_PRODUCTS_STARTED",
    FETCH_PRODUCTS_SUCCESS: "FETCH_PRODUCTS_SUCCESS",
    FETCH_PRODUCTS_FAILURE: "FETCH_PRODUCTS_FAILURE",
  
    ADD_PRODUCT: "ADD_PRODUCT",
    ADD_PRODUCT_STARTED: "ADD_PRODUCT_STARTED",
    ADD_PRODUCT_SUCCESS: "ADD_PRODUCT_SUCCESS",
    ADD_PRODUCT_FAILURE: "ADD_PRODUCT_FAILURE",
  };

export const WALLET = {
  FETCH_WALLET: "FETCH_WALLET",
  FETCH_WALLET_STARTED: "FETCH_WALLET_STARTED",
  FETCH_WALLET_SUCCESS: "FETCH_WALLET_SUCCESS",
  FETCH_WALLET_FAILURE: "FETCH_WALLET_FAILURE",

  UPDATE_WALLET: "UPDATE_WALLET",
  UPDATE_WALLET_STARTED: "UPDATE_WALLET_STARTED",
  UPDATE_WALLET_SUCCESS: "UPDATE_WALLET_SUCCESS",
  UPDATE_WALLET_FAILURE: "UPDATE_WALLET_FAILURE",
};

export const TRANSACTION = {
  FETCH_TRANSACTIONS: "FETCH_TRANSACTIONS",
  FETCH_TRANSACTIONS_STARTED: "FETCH_TRANSACTIONS_STARTED",
  FETCH_TRANSACTIONS_SUCCESS: "FETCH_TRANSACTIONS_SUCCESS",
  FETCH_TRANSACTIONS_FAILURE: "FETCH_TRANSACTIONS_FAILURE",

  ADD_TRANSACTION: "ADD_TRANSACTION",
  ADD_TRANSACTION_STARTED: "ADD_TRANSACTION_STARTED",
  ADD_TRANSACTION_SUCCESS: "ADD_TRANSACTION_SUCCESS",
  ADD_TRANSACTION_FAILURE: "ADD_TRANSACTION_FAILURE",
};

export default PROFILE = {
  FETCH_PROFILE: "FETCH_PROFILE",
  FETCH_PROFILE_STARTED: "FETCH_PROFILE_STARTED",
  FETCH_PROFILE_SUCCESS: "FETCH_PROFILE_SUCCESS",
  FETCH_PROFILE_FAILURE: "FETCH_PROFILE_FAILURE",

  UPDATE_PROFILE: "UPDATE_PROFILE",
  UPDATE_PROFILE_STARTED: "UPDATE_PROFILE_STARTED",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_FAILURE: "UPDATE_PROFILE_FAILURE",
};
