export default AUTH = {
  FETCH_AUTH: "FETCH_AUTH",
  FETCH_AUTH_STARTED: "FETCH_AUTH_STARTED",
  FETCH_AUTH_SUCCESS: "FETCH_AUTH_SUCCESS",
  FETCH_AUTH_FAILURE: "FETCH_AUTH_FAILURE",

  LOGIN: "LOGIN",
  LOGIN_STARTED: "LOGIN_STARTED",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  SIGNUP: "SIGNUP",
  SIGNUP_STARTED: "SIGNUP_STARTED",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",

  LOGOUT: "LOGOUT",
  LOGOUT_STARTED: "LOGOUT_STARTED",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};
