export default SHOP = {
  REGISTER_SHOP: "REGISTER_SHOP",
  REGISTER_SHOP_STARTED: "REGISTER_SHOP_STARTED",
  REGISTER_SHOP_SUCCESS: "REGISTER_SHOP_SUCCESS",
  REGISTER_SHOP_FAILURE: "REGISTER_SHOP_FAILURE",
  FETCH_SHOPS: "FETCH_SHOPS",
  FETCH_SHOPS_STARTED: "FETCH_SHOPS_STARTED",
  FETCH_SHOPS_SUCCESS: "FETCH_SHOPS_SUCCESS",
  FETCH_SHOPS_FAILURE: "FETCH_SHOPS_FAILURE",
};
